/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TempleOfKnowledgeRouteImport } from './routes/temple-of-knowledge'
import { Route as WhackAQuestionRouteImport } from './routes/whack-a-question'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TempleOfKnowledgeRoute = TempleOfKnowledgeRouteImport.update({
  id: '/temple-of-knowledge',
  path: '/temple-of-knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const WhackAQuestionRoute = WhackAQuestionRouteImport.update({
  id: '/whack-a-question',
  path: '/whack-a-question',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/temple-of-knowledge': typeof TempleOfKnowledgeRoute
  '/whack-a-question': typeof WhackAQuestionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/temple-of-knowledge': typeof TempleOfKnowledgeRoute
  '/whack-a-question': typeof WhackAQuestionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/temple-of-knowledge': typeof TempleOfKnowledgeRoute
  '/whack-a-question': typeof WhackAQuestionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/temple-of-knowledge' | '/whack-a-question'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/temple-of-knowledge' | '/whack-a-question'
  id: '__root__' | '/' | '/temple-of-knowledge' | '/whack-a-question'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TempleOfKnowledgeRoute: typeof TempleOfKnowledgeRoute
  WhackAQuestionRoute: typeof WhackAQuestionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temple-of-knowledge': {
      id: '/temple-of-knowledge'
      path: '/temple-of-knowledge'
      fullPath: '/temple-of-knowledge'
      preLoaderRoute: typeof TempleOfKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whack-a-question': {
      id: '/whack-a-question'
      path: '/whack-a-question'
      fullPath: '/whack-a-question'
      preLoaderRoute: typeof WhackAQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TempleOfKnowledgeRoute: TempleOfKnowledgeRoute,
  WhackAQuestionRoute: WhackAQuestionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
