/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JuegoMemoriaRouteImport } from './routes/juego-memoria'
import { Route as JuegoTriviaRouteImport } from './routes/juego-trivia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegoMemoriaRoute = JuegoMemoriaRouteImport.update({
  id: '/juego-memoria',
  path: '/juego-memoria',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegoTriviaRoute = JuegoTriviaRouteImport.update({
  id: '/juego-trivia',
  path: '/juego-trivia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/juego-memoria': typeof JuegoMemoriaRoute
  '/juego-trivia': typeof JuegoTriviaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/juego-memoria': typeof JuegoMemoriaRoute
  '/juego-trivia': typeof JuegoTriviaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/juego-memoria': typeof JuegoMemoriaRoute
  '/juego-trivia': typeof JuegoTriviaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/juego-memoria' | '/juego-trivia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/juego-memoria' | '/juego-trivia'
  id: '__root__' | '/' | '/juego-memoria' | '/juego-trivia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JuegoMemoriaRoute: typeof JuegoMemoriaRoute
  JuegoTriviaRoute: typeof JuegoTriviaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juego-memoria': {
      id: '/juego-memoria'
      path: '/juego-memoria'
      fullPath: '/juego-memoria'
      preLoaderRoute: typeof JuegoMemoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juego-trivia': {
      id: '/juego-trivia'
      path: '/juego-trivia'
      fullPath: '/juego-trivia'
      preLoaderRoute: typeof JuegoTriviaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JuegoMemoriaRoute: JuegoMemoriaRoute,
  JuegoTriviaRoute: JuegoTriviaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
